### ISSUE TITLE
GCS support

### ISSUE THREAD

**Issue by jnewland** [urcomputeringpal/label-mutex#11]
see https://github.com/mco-gh/gcslock
```[tasklist]
### Tasks
- [x] https://github.com/fsouza/fake-gcs-server
- [x] lock library
- [x] integration
- [x] configuration
- [ ] https://github.com/urcomputeringpal/label-mutex-test/pull/1
- [ ] https://github.com/urcomputeringpal/label-mutex/pull/19
- [ ] polish, announcement, release
```
